package ru.innopolis.lexer;

public enum TokenType {
    ROUTINE, VAR, IS, TYPE, RECORD, ARRAY, WHILE, LOOP,
    FOR, IN, REVERSE, IF, THEN, ELSE, END, PRINT, RETURN, AS,

    INTEGER, REAL, BOOLEAN, STRING,

    TRUE, FALSE,

    PLUS, MINUS, MULT, DIV, MOD, EQUAL, NOT_EQUAL, LESS, GREATER,
    LESS_EQUAL, GREATER_EQUAL, AND, OR, XOR, NOT, ASSIGN,

    LPAREN, RPAREN, LBRACKET, RBRACKET, COLON, COMMA, DOT, DOT_DOT,

    IDENTIFIER, INT_LITERAL, REAL_LITERAL, STRING_LITERAL,

    EOF
}
